# Generated by Django 5.0.14 on 2025-05-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrituracoes', '0002_zfiscal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zfiscal',
            name='cgc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
