# Generated by Django 5.0.14 on 2025-05-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrituracoes', '0003_alter_zfiscal_cgc'),
    ]

    operations = [
        migrations.CreateModel(
            name='FBL3N',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atribuicao', models.CharField(blank=True, max_length=50, null=True)),
                ('empresa', models.CharField(blank=True, max_length=10, null=True)),
                ('conta_razao', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('divisao', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('referencia', models.CharField(blank=True, max_length=50, null=True)),
                ('data_lancamento', models.DateField(blank=True, null=True)),
                ('data_documento', models.DateField(blank=True, null=True)),
                ('chave_lancamento', models.CharField(blank=True, max_length=50, null=True)),
                ('montante_moeda_interna', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('moeda_interna', models.CharField(blank=True, max_length=10, null=True)),
                ('doc_compensacao', models.CharField(blank=True, max_length=50, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('centro_custo', models.CharField(blank=True, max_length=50, null=True)),
                ('nome_usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('elemento_pep', models.CharField(blank=True, max_length=50, null=True)),
                ('periodo_contabil', models.CharField(blank=True, max_length=10, null=True)),
                ('pedido', models.CharField(blank=True, max_length=50, null=True)),
                ('contrato', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'fbl3n',
            },
        ),
    ]
